# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PDCimpresora.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.   Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(377, 283)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background-color:#aaa;\n"
"}")
        # CORRECTED LINES BELOW:
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel) # Changed from QtCore.Qt.QFrame.Shape.StyledPanel
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)     # Changed from QtCore.Qt.QFrame.Shadow.Raised
        # END OF CORRECTED LINES
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 371, 31))
        self.label.setStyleSheet("QLabel {\n"
"    qproperty-alignment: 'AlignHCenter | AlignVCenter';\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 30, 377, 252))
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color:#ccc;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel) # Assuming similar issue here if not fixed
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)     # Assuming similar issue here if not fixed
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 49, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(40, 70, 49, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(40, 100, 71, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(40, 130, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.lineEditNombre = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditNombre.setGeometry(QtCore.QRect(140, 40, 111, 21))
        self.lineEditNombre.setObjectName("lineEditNombre")
        self.lineEditApellido = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditApellido.setGeometry(QtCore.QRect(140, 70, 113, 21))
        self.lineEditApellido.setObjectName("lineEditApellido")
        self.lineEditNroDeTurno = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditNroDeTurno.setGeometry(QtCore.QRect(140, 100, 113, 21))
        self.lineEditNroDeTurno.setObjectName("lineEditNroDeTurno")
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Panel de control IMPRESORA"))
        self.label_2.setText(_translate("MainWindow", "Nombre:"))
        self.label_3.setText(_translate("MainWindow", "Apellido:"))
        self.label_4.setText(_translate("MainWindow", "Nro de turno:"))
        self.pushButton.setText(_translate("MainWindow", "Imprimir"))