# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PDCimpresora.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(433, 383)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background-color:#aaa;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 371, 31))
        self.label.setStyleSheet("QLabel {\n"
"    qproperty-alignment: \'AlignHCenter | AlignVCenter\';\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(10, 30, 411, 341))
        self.frame_4.setStyleSheet("QFrame{\n"
"background-color:#ccc;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(40, 170, 49, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(40, 200, 49, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(40, 230, 121, 16))
        self.label_14.setObjectName("label_14")
        self.btnImprimir = QtWidgets.QPushButton(self.frame_4)
        self.btnImprimir.setGeometry(QtCore.QRect(160, 290, 75, 24))
        self.btnImprimir.setObjectName("btnImprimir")
        self.txtNombrePaciente = QtWidgets.QLineEdit(self.frame_4)
        self.txtNombrePaciente.setGeometry(QtCore.QRect(160, 170, 111, 21))
        self.txtNombrePaciente.setObjectName("txtNombrePaciente")
        self.txtDniPaciente = QtWidgets.QLineEdit(self.frame_4)
        self.txtDniPaciente.setGeometry(QtCore.QRect(160, 200, 113, 21))
        self.txtDniPaciente.setObjectName("txtDniPaciente")
        self.txtNacimiento = QtWidgets.QLineEdit(self.frame_4)
        self.txtNacimiento.setGeometry(QtCore.QRect(160, 230, 113, 21))
        self.txtNacimiento.setObjectName("txtNacimiento")
        self.txtNombreHospital = QtWidgets.QLineEdit(self.frame_4)
        self.txtNombreHospital.setGeometry(QtCore.QRect(150, 40, 113, 21))
        self.txtNombreHospital.setObjectName("txtNombreHospital")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(40, 40, 71, 16))
        self.label_15.setObjectName("label_15")
        self.boxDimensionesImpresion = QtWidgets.QComboBox(self.frame_4)
        self.boxDimensionesImpresion.setGeometry(QtCore.QRect(150, 70, 221, 22))
        self.boxDimensionesImpresion.setObjectName("boxDimensionesImpresion")
        self.boxDimensionesImpresion.addItem("")
        self.boxDimensionesImpresion.addItem("")
        self.boxDimensionesImpresion.addItem("")
        self.boxDimensionesImpresion.addItem("")
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(40, 70, 101, 16))
        self.label_16.setObjectName("label_16")
        self.labelFullMed = QtWidgets.QLabel(self.frame)
        self.labelFullMed.setGeometry(QtCore.QRect(270, 10, 49, 16))
        self.labelFullMed.setObjectName("labelFullMed")
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Panel de control IMPRESORA"))
        self.label_12.setText(_translate("MainWindow", "Nombre:"))
        self.label_13.setText(_translate("MainWindow", "dni:"))
        self.label_14.setText(_translate("MainWindow", "fecha de nacimiento:"))
        self.btnImprimir.setText(_translate("MainWindow", "Imprimir"))
        self.label_15.setText(_translate("MainWindow", "hospital:"))
        self.boxDimensionesImpresion.setItemText(0, _translate("MainWindow", "2.25 x 1.25 (Pulsera hospitalaria)"))
        self.boxDimensionesImpresion.setItemText(1, _translate("MainWindow", "ninguna"))
        self.boxDimensionesImpresion.setItemText(2, _translate("MainWindow", "3 x 2 (mediana) "))
        self.boxDimensionesImpresion.setItemText(3, _translate("MainWindow", "4 x 6 (grande, típica de envíos)"))
        self.label_16.setText(_translate("MainWindow", "dimensiones:"))
        self.labelFullMed.setText(_translate("MainWindow", "Fullmed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
